version: '3.7'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
volumes:
  sql-data:
