// <auto-generated />
using System;
using ArchLab4.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchLab4.Migrations
{
    [DbContext(typeof(ArchDbContext))]
    [Migration("20231016135043_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arch4Platform.Employee", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Name = "John",
                            Title = "Manager"
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Name = "Alice",
                            Title = "Developer"
                        });
                });

            modelBuilder.Entity("Arch4Platform.TaskEntity", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            Description = "Description 2",
                            EmployeeId = 2L,
                            IsCompleted = true,
                            Name = "Task 2"
                        },
                        new
                        {
                            Id = 1L,
                            Description = "Description 1",
                            EmployeeId = 1L,
                            IsCompleted = false,
                            Name = "Task 1"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Description 3",
                            EmployeeId = 1L,
                            IsCompleted = false,
                            Name = "Task 3"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Description 4",
                            EmployeeId = 2L,
                            IsCompleted = true,
                            Name = "Task 4"
                        });
                });

            modelBuilder.Entity("Arch4Platform.TaskEntity", b =>
                {
                    b.HasOne("Arch4Platform.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Arch4Platform.Employee", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
